---
# tasks file for 20_provision_aws_resources

# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/template_module.html
# Template to create control files

- name: Provision AWS resources
  block:
    - name: 10 - Create terraform manifest
      ansible.builtin.template:
        src: main.j2
        dest: "{{playbook_dir}}/workspace/main.tf"

    - name: 20 - Format main.tf
      command: terraform -chdir="{{playbook_dir}}/workspace" fmt

    - name: 30 - Terraform init
      command: terraform -chdir="{{playbook_dir}}/workspace" init

    - name: 40 - Terraform validation
      command: terraform -chdir="{{playbook_dir}}/workspace" validate

    - name: 50 - Set var
      set_fact:
        ANSIBLE_STDOUT_CALLBACK: "debug"

    - name: 60 - Terraform plan
      command: terraform -chdir="{{playbook_dir}}/workspace" plan -out="{{ project.name }}_plan.out"

    - name: 70 - Terraform plan show
      command: terraform -chdir="{{playbook_dir}}/workspace" show -no-color "{{ project.name }}_plan.out"
      register: t_plan

    # To make it human readable you have to setup parameters in /etc/ansible/ansible.cfg
    # bin_ansible_callbacks = True
    # stdout_callback = yaml
    - name: 80 - Print plan
      vars:
        ANSIBLE_STDOUT_CALLBACK: "debug"
      debug: msg="{{ t_plan.stdout }}"
    # - name: 90 - Terraform apply
    #   command: terraform -chdir="{{playbook_dir}}/workspace" apply -auto-approve {{ project.name }}_plan.out
    #   register: t_apply

    # - name: 100 - Print apply
    #   vars:
    #     ANSIBLE_STDOUT_CALLBACK: "debug"
    #   debug: msg="{{ t_apply.stdout }}"
  tags:
    - init_terraform
