---
# tasks file for 70_data_enc

- name: Encryption
  block:
    - name: 10 - Generate encription key
      ansible.builtin.shell: head -c 32 /dev/urandom | base64
      register: encription_key

    - name: 20 - Generate encription confg file
      ansible.builtin.template:
        src: "encryption-config.yaml.j2"
        dest: "{{ playbook_dir }}/workspace/{{ project.name }}/certs/encryption-config.yaml"
        mode: 0644

  when: "'local' in group_names"
  tags:
    - encryption

- name: Copy
  block:
    - name: 30 - Copy encription config to controllers
      copy: src={{ playbook_dir }}/workspace/{{ project.name }}/certs/encryption-config.yaml dest="/home/{{ ansible_user }}/encryption-config.yaml" mode=0644
      when: "'controller' in group_names"
  tags:
    - encryption
