---
# tasks file for 70_data_enc

- name: Encryption
  block:
    - name: 10 - Generate encription key
      copy: src=./ dest="{{ playbook_dir }}/workspace/{{ project.name }}/certs" mode=0777
      register: transfer_scripts

    # - name: 30 - Generate encription confg file
    #   ansible.builtin.template:
    #     src: "encr"
    #     dest: "{{ playbook_dir }}/workspace/{{ project.name }}/certs/{{ item }}-csr.json"
    #     mode: 0644
    #   with_items:

    # - name: 10 - Transfer scripts
    #   copy: src=./ dest="{{ playbook_dir }}/workspace/{{ project.name }}/certs" mode=0777
    #   register: transfer_scripts

    # - name: 20 - Execute encryption and copy to controllers
    #   command: /bin/bash {{ item }} {{ playbook_dir }} {{ project.name }}
    #   args:
    #     chdir: "{{ playbook_dir }}/workspace/{{ project.name }}/certs"
    #   with_items:
    #     - encryption.sh
    #     - encryption_copy.sh
  tags:
    - encryption
