---
# tasks file for 60_copy_config

- name: Copy to target
  block:
    - name: 10 - Execute worker
      command: /bin/bash {{ item }} {{ playbook_dir }} {{ project.name }}
      args:
        chdir: "{{ playbook_dir }}/workspace/{{ project.name }}/certs"
      with_items:
        - copy2worker.sh

    - name: 20 - Execute controller
      command: /bin/bash {{ item }} {{ playbook_dir }} {{ project.name }}
      args:
        chdir: "{{ playbook_dir }}/workspace/{{ project.name }}/certs"
      with_items:
        - copy2controller.sh
  tags:
    - copy_config
